feat: add tibia_urls field into information-section
TibiaData/tibiadata-api-go pull request #398
Opened 2024-10-15 16:35 UTC by Kai-Animator

This pull request addresses **Issue #381** by adding the `Link` field to the `Information` section in all API responses. The `Link` field provides a direct URL to the source data on the official Tibia website.

**Changes Overview:**

- **Updated `Information` Struct:**
  - Added a new `Link` field to the `Information` struct in `webserver.go`:
    ```go
    type Information struct {
        APIDetails APIDetails `json:"api"`       // The API details.
        Timestamp  string     `json:"timestamp"` // The timestamp from when the data was processed.
        Link       string     `json:"link"`      // The link to the source of the data.
        Status     Status     `json:"status"`    // The response status information.
    }
    ```
- **Modified API Handlers:**
  - Updated all API endpoint handlers to populate the `Link` field with the appropriate URL pointing to the source data.
  
  - Example from `TibiaWorldsWorld.go`:
  
    ```go
    return WorldResponse{
        World: World{
            // ... existing fields ...
        },
        Information: Information{
            APIDetails: TibiaDataAPIDetails,
            Timestamp:  TibiaDataDatetime(""),
            Link:       "https://www.tibia.com/community/?subtopic=worlds&world=" + world,
            Status: Status{
                HTTPCode: http.StatusOK,
            },
        },
    }, nil
    ```

**Testing:**

- Tested all modified endpoints to ensure the `Link` field is correctly populated.
- Verified that the URLs are accurate and lead to the correct pages on Tibia.com.

---

**Notes:**

- NewsList was kind of tricky to handle the different patterns so I decided to sum all different URLs into only "https://www.tibia.com/news/?subtopic=newsarchive"

- This is my first PR in the project so I am open to feedback and willing to make any necessary changes to meet the project's standards.

fix #381

2024-10-15 18:48 UTC, tobiasehlert requested changes
Thanks for the PR @Kai-Animator, this is a good start!
There are some things that I'd like to be adjusted.

One of them is that there is already a link for every endpoints source available, so hardcoding the line in the "Link" field is not optimal. It would be better to have it being populated by the value set in "tibiadataRequest.URL" before being sent to tibiaDataRequestHandler.

For instance here:
https://github.com/TibiaData/tibiadata-api-go/blob/a4afbe1bf78013effcdf6e71605d31811374531b/src/webserver.go#L394-L407

I'd also like the "Link" to be named "TibiaURL" instead, since that's a slightly better description of that it is.
Also, we should probably want to have a []string as well, in case we add multi-upstream sources.

2024-10-15 18:48 UTC, tobiasehlert commented on src/webserver.go
> +	Link       string     `json:"link"`      // The link to the source of the data.
```suggestion
	TibiaURL   []string   `json:"tibia_url"` // The links to the sources of the data on tibia.com.
```

2024-10-15 18:48 UTC, tobiasehlert commented on src/webserver.go
> +			Link:       "-",
```suggestion
			TibiaURL:   []string{},
```

2024-10-15 18:48 UTC, tobiasehlert commented on src/webserver.go
> +		Link:       "-",
```suggestion
		TibiaURL:   []string{},
```

2024-10-15 22:05 UTC, Kai-Animator commented
Thanks for the review @tobiasehlert . I will work on it 👍

2024-10-16 10:53 UTC, Kai-Animator commented
Hi @tobiasehlert  :wave: 

I’ve implemented the changes you requested:

- The "Link" field is now populated using the value from `tibiadataRequest.URL` before it's sent to `tibiaDataRequestHandler`, rather than hardcoding the URL. (Newslist and HousesOverview might need refactor)
- Renamed "Link" to "TibiaURL".
- I've also updated the field to support a `[]string` for multi-upstream sources in the future (HousesOverview is using multiple URLs now).

Please let me know if there’s anything else :]

2024-10-23 02:57 UTC, phenpessoa commented
Since this is now slice, I think it should probably be named `TibiaURLs`, plural.

2024-10-24 22:12 UTC, tobiasehlert commented
Yeah good input @phenpessoa. 👍

2024-10-25 21:06 UTC, phenpessoa commented
The field name was updated but the json is still called `tibia_url`. I think it should probably be `tibia_urls`.

2024-10-26 14:30 UTC, Kai-Animator commented
> The field name was updated but the json is still called `tibia_url`. I think it should probably be `tibia_urls`.

Hey @phenpessoa, thanks for looking at the code, is this the change that you mentioned?

2024-10-27 02:02 UTC, phenpessoa commented
Yup! Looks good.

2024-10-28 06:59 UTC, tobiasehlert reviewed
We are getting closer! 🚀
The news endpoints just need some adjustment, but then we should be really to rock.

2024-10-28 06:59 UTC, tobiasehlert commented on src/TibiaNews.go
> +	TibiaURLs    string `json:"url"`             // The URL for the news with id.
This is supposed to be one URL for the news entry.

2024-10-28 06:59 UTC, tobiasehlert commented on src/TibiaNews.go
> +	NewsData.TibiaURLs = rawUrl
This is supposed to be one here as well.

2024-10-28 06:59 UTC, tobiasehlert commented on src/TibiaNews_test.go
> +	assert.Equal("https://www.tibia.com/news/?subtopic=newsarchive&id=6512", newsArticleJson.News.TibiaURLs)
Same as above

2024-10-28 06:59 UTC, tobiasehlert commented on src/TibiaNews_test.go
> +	assert.Equal("https://www.tibia.com/news/?subtopic=newsarchive&id=6529", newsArticleJson.News.TibiaURLs)
Same as above

2024-10-28 06:59 UTC, tobiasehlert commented on src/TibiaNews_test.go
> +	assert.Equal("https://www.tibia.com/news/?subtopic=newsarchive&id=504", newsArticleJson.News.TibiaURLs)
Same as above

2024-10-28 06:59 UTC, tobiasehlert commented on src/TibiaNews_test.go
> +	assert.Equal("https://www.tibia.com/news/?subtopic=newsarchive&id=6481", newsArticleJson.News.TibiaURLs)
Same as above

2024-10-28 06:59 UTC, tobiasehlert commented on src/TibiaNewslist.go
> +	TibiaURLs string `json:"url"`               // The URL for the news with id.
Same as above

2024-10-28 06:59 UTC, tobiasehlert commented on src/TibiaNewslist.go
> +		OneNews.TibiaURLs = NewsSplit[0] + NewsID
Same as above

2024-10-28 06:59 UTC, tobiasehlert commented on src/TibiaNewslist_test.go
> +	assert.Equal("https://www.tibia.com/news/?subtopic=newsarchive&id=6529", firstArticle.TibiaURLs)
Same as above

2024-10-28 12:21 UTC, Kai-Animator commented
Thanks for the feedback @tobiasehlert, sorry search and replace all because I though you weren't using TibiaURL in other files. 🙇 Hope this revisions are satisfying.

2024-11-21 22:06 UTC, tobiasehlert approved these changes
looks good to me 🌟

2024-11-21 22:07 UTC, merged